name: AKS Scaling-up

on:
  workflow_dispatch:
  push:

jobs:
  scale-aks-node:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # ✅ Required for OIDC login
      contents: read    # ✅ Required for accessing repo contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login  # ✅ OIDC-based authentication (No manual login required)
        run: az login --use-device-code

      - name: Set Environment Variables  # ✅ Corrected secret references
        run: |
          echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}" >> $GITHUB_ENV
          echo "CLUSTER_RESOURCE_GROUP=${{ secrets.RESOURCE_GROUP_NAME }}" >> $GITHUB_ENV

      - name: Scale AKS Node Pool Up  # ✅ Using variables correctly
        run: |
          az aks nodepool scale \
            --resource-group $CLUSTER_RESOURCE_GROUP \
            --cluster-name $CLUSTER_NAME \
            --nodepool-name agentpool \
            --node-count 2
