name: AKS Scaling-up

on:
  workflow_dispatch:
  push:

jobs:
  scale-aks-node:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Azure Login
        run: az login --use-device-code

      - name : set env variable
        run: |
          echo "CLUSTER_NAME= ${{ secret.CLUSTER_NAME }}" >> $GITHUB_ENV
          echo "CLUSTER_RESOURCE_GROUP= ${{ secret.RESOURCE_GROUP_NAME }}" >> $GITHUB_ENV

      - name: scale aks node up
        run: az aks nodepool scale --resource-group $CLUSTER_RESOURCE_GROUP --cluster-name $CLUSTER_NAME --nodepool-name agentpool --node-count 1   
