name: AKS Scaling-up

on:
  workflow_dispatch:
  push:

jobs:
  scale-aks-node:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # ✅ Required for OIDC login
      contents: read    # ✅ Required for accessing repo contents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        # uses: azure/login@v2
        # with:
        #   client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #   tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #   subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   enable-AzPSSession: false
        #   environment: azurecloud
        #   allow-no-subscriptions: false
        #   audience: api://AzureADTokenExchange
        #   auth-type: SERVICE_PRINCIPAL
        run: az login --use device-code

